# For more Configuration Options visit - https://gohugo.io/overview/configuration/
#
#
config                               = "config.toml"
metaDataFormat                       = "toml" # "yaml", "toml", "json"
languageCode                         = "en-us"
defaultContentLanguage               = "en-us"
title                                = "Weave Static Website"
baseurl                              = "http://weaveiq.com/"
googleAnalytics                      = "UA-93663741-1"
archetypeDir                         = "archetypes"
staticDir                            = "static"
layoutDir                            = "layouts"
log                                  = false  # Enable Logging
buildDrafts                          = false  # include content marked as draft
enableRobotsTXT                      = true   # Build robots.txt file
disable404                           = false  # Do not render 404 page
enableMissingTranslationPlaceholders = false  # Show a placeholder instead of the default value or an empty string if a translation is missing



[params]
    AuthorName         = "Marcos Martinez"
    SiteDesc           = "Weave Static Website"
    tags               = ["updates", "community", "news", "industry", "technology"]
    googleFontFamilies = "Raleway|Dosis|Lato|Josefin Sans|Abel|Material Icons" # for more fonts visit: https://fonts.google.com. For more fonts visit: https://material.io/icons/ Do NOT remove "Material Icons" fonts

[taxonomies]
    category           = "categories"

[permalinks]
    post = "/:year/:slug"
